##This file contains new methods for the R package
retlev <- function(fitted, ...)
  UseMethod("retlev")
qq <- function(fitted, ...)
  UseMethod("qq")
pp <- function(fitted, ...)
  UseMethod("pp")
dens <- function(fitted, ...)
  UseMethod("dens")
convassess <- function(fitted, n = 50)
  UseMethod("convassess")
